### PR TITLE
Size and shape Patho Module

### PR DESCRIPTION
**Pull request by zarquon42b**
This PR contains the Size and Shape patho module for skulls.

### CODE REVIEW

**Review by cuboideum — CHANGES_REQUESTED** [review]
## Required Changes With the PBP App

### Evaluation of Completeness Criteria

The criteria for the creation of a skull ROI specification are

1.all ROIs of the frontal bone need not to be scored as 'missing'
2. at least one parietal bone needs not to be scored as 'missing'

Currently, it is possible to create a Size&Shape section with all frontal bone ROIs being scored as 'missing'. Also, it is possible to create a section with both parietal bones being scored as 'missing'. 

This indicates that the criteria are currently not properly evaluated.

The error message for skeletal inventories with all skull ROIs being scored as 'missing' is "At least one Bone associated with the ROI must be present". This criterion seems to be currently implemented.

### Presence of Craniostenosis

The value specification should accept up to four categorical labels. Currently not more than one label can be specified.

### Presence of Hydrocephaly

In the GUI, the data field is labelled 'Presence of Acromegaly'.

## Required Changes With RDFBones-Graphics

### Value Specifications

The drawings for the Size&Shape value specifications are currently in the file 'phaleron-patho_SizeAndShape_NetworkGraphics.svg'. These tabs need to be moved to the file 'phaleron-patho_SizeAndShape_NetworkGraphics.svg'.

**Comment by cuboideum** [comment]
Changes requested in Review and pertaining to the RDFBones-Graphics repository have been carried out with issue https://github.com/RDFBones/RDFBonesGraphics/commit/5e5566839e60e35f4133cc170c7a7b3a946bcf7c.

**Review by cuboideum — APPROVED** [review]
Looks good.

**Comment by zarquon42b** [comment]
Found error in delete query and fixed it.

**Comment by zarquon42b** [comment]
Added entire Size and Shape module. Please recheck.

**Review by cuboideum — CHANGES_REQUESTED** [review]
The ROI specifications are connected to the dataset sections via 'has part' instead of 'is about'.

**Comment by cuboideum** [comment]
Issues resolved in personal communication. The property 'has part' is kept to be consistent with 'bone addition' sections.

**Pull request merged**
