### PR TITLE
Vertebral patho

### PR DESCRIPTION
**Pull request by zarquon42b**
Implements Vertebral Pathologies

### CODE REVIEW

**Review by cuboideum — CHANGES_REQUESTED** [review]
The following issues need fixing:

- For 'Surface Of Body Of Vertebra Affected By Osteophytes' it should be possible to select one or two category labels
- For 'Surface Of Body Of Vertebra Affected By Schmorls Nodes' it should be possible to select one or two category labels

I would suggest the following enhancements:

- Rename 'Select ROI Affected by Ankylosis' to 'Select other skeletal elements that are permanently connected by ankylosis to the skeletal element currently investigated'.
- Add note to 'Select ROI Affected by Ankylosis': 'Only select elements from adjacent vertebrae.'
- The dataset section instances are about the instance of the relevant ROI group (here: 'Phaleron vertebral columns anatomical regions of interest group'). This is not necessary, the restriction to the class is just to indicate how list boxes should be populated. But I assume this is in line with the implementation of other modules?

Input is not required for 'Select ROI Affected by Ankylosis'. If this item appears, ankylosis is clearly present. But might there be cases where it is unclear which other element is ankylosed? I am undecided.

**Review by cuboideum — CHANGES_REQUESTED** [review]
Availability of the ankylosis item is inconsistent. Expected behaviour is that an additional 'Ankylosis' control appears if either 'Degree of osteophyte formation' or 'Degree of syndesmophyte formation' is scored as 'Ankylosis'. Instead, the optional appearance of the control seems to be exclusively bound to 'Degree of osteophyte formation.

Follow the following steps to reproduce the problem:

1. Create a new 'vertebral pathologies' dataset section. Score 'Degree of osteophyte formation' as anything but 'Ankylosis' (e.g. 'Barely discernible'). Score 'Degree of syndesmophyte formation' as 'Ankylosis'.
2. Fill in the other items in the section and save changes. Additional controls might be displayed depending on the input but there is no option to specify ankylosed elements.
3. Change the score of 'Degree of osteophyte formation' to 'Ankylosis' and the score for 'Degree of syndesmophyte formation' to 'Barely discernible'.
4. Save changes. This causes the option for specifying ankylosed elements to appear.
5. The behaviour is the same when a new section is initiated with "Degree of osteophyte formation' set to 'Ankylosis' and 'Degree of syndesmophyte formation' to some other value. The 'Ankylosis' control appears then but disappears if the scores are swapped. Scoring both items as 'Ankylosis' lets the additional control appear as expected.

**Comment by zarquon42b** [comment]
Thanks for the nice report. Yes, you are right, I accidentally tied it to the wrong second class.
Please retry now.

**Comment by cuboideum** [comment]
Commit https://github.com/AnthroGraph/PBP-App/pull/35/commits/c1a7c07d7006689a20e7a52233b0e2f7f0fa1c5b has fixed the visibility of 'Ankylosis' control issue.

**Pull request merged**
