### PR TITLE
Dental patho

### PR DESCRIPTION
**Pull request by zarquon42b**
This implements the dental pathology. For testing, please use the UI-Toc branch of RDFBones-App: https://github.com/AnthroGraph/RDFBones-App/tree/UI-Toc.

### CODE REVIEW

**Comment by zarquon42b** [comment]
Apart from implementing dental pathology, this PR contains a large amount of improvements regarding usability. Therefore, please test this intensively: Create (dental and osteological) Skeletal Inventories, fill some of the stuff and then add respective pathologies and report back potential issues.
Especially the Skeletal Inventories have become much more manageable by only loading one tab at a time instead of everything at once.

**Comment by zarquon42b** [comment]
NOTE: Please install latest master branch of RDFBones-App and latest PhaleronApp-Ontology before testing!!

**Review by cuboideum — CHANGES_REQUESTED** [review]
During testing I have made the following observations:

Skeletal inventory:

* Miscellaneous
     * Overall preservation
          * **Items are not sorted**
     * Percentage of skeleton present
          * **Items are not sorted**
* Most sections
     * Taphonomy
          * **Items are not sorted**
Dental inventory:

* Most sections
     * Dental wear
          * **Items not properly sorted** (cf. [RDFBones-O #159](https://github.com/RDFBones/RDFBones-O/issues/159))

Dental Pathologies:

* 'Create New PBP-Dental-Paleopathology Instance'
     * After saving the dental inventory selection the page needs to be updated manually for the new instance to appear in the table below.
* Most tabs
     * Alveolar resorption
          * **Items not properly sorted**
          * **Sorting order for M2 differs from M3 and M1**
          * **No label for item ThreeToFiveMillimeters'**
          * **Superfluous item AlveolarResorption**
     * Abscess
          * Items not properly sorted but usable
     * Hypoplasia
          * Items not properly sorted but usable
          * **Multiple selection required but not provided**
     * Presence of Calculus
          * Items not properly sorted but usable
     * Caries
          * Items not properly sorted but usable
          * **Multiple selection required but not provided**

Observations that definitely need fixing I have formatted bold. @zarquon42b and I have already discussed today what might be causes for these irregularity. This will determine where issues will have to be created.

**Comment by zarquon42b** [comment]
All issues mentioned above, except the multiple entry possiblities in Hypoplasia and Caries are tied to Ontology issues. This arises from the fact that: 

- Not all labels are referenced in a sorting directive
- If they are, the sorting directives are not linked to appropriate VS classes via restrictions
### Solution 1 

- make sorting directives mandatory 
- make restrictions of sorting directives to applicable VS mandatory

### Solution 2
Modify forms and pass sorting directive manually (which is nor really feasible given the amount of forms already implemented).
However, this would also make the sorting directive mandatory. If they were optional, the sorting would prefer those without directives because the sorting favors empty strings.

**Comment by zarquon42b** [comment]
> Dental Pathologies:
>
>     'Create New PBP-Dental-Paleopathology Instance'
>         After saving the dental inventory selection the page needs to be updated manually for the new instance to appear in the table below.
> 

This is not an issue, as creating a new instances directs to that new instance. No need to refresh the page.

**Comment by zarquon42b** [comment]
I fixed issues related to the implementation:

- Hypoplasia 
   -  Multiple selection required but not provided

- Caries
   -  Multiple selection required but not provided

**Comment by 15E601** [comment]
I have tested entering data and see no obvious issues.

**Pull request merged**
